version: '3.8'

services:
  # 1. The Django Web Server
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # OVERRIDE: Tell Django to find Redis at the hostname 'redis', not '127.0.0.1'
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  # 2. The Background Worker (Celery)
  worker:
    build: .
    # 'gevent' pool is stable for I/O bound tasks
    command: celery -A config worker -l info --pool=gevent --concurrency=10
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      # OVERRIDE: Tell Celery to find Redis at the hostname 'redis'
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  # 3. The Broker (Redis)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always